# Generated by Django 6.0.2 on 2026-03-10 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_company_is_verified_companyverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Rotational', 'Rotational')], max_length=50)),
                ('work_duration', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('openings', models.PositiveIntegerField()),
                ('job_category', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('key_skills', models.TextField()),
                ('job_highlights', models.TextField()),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
