# Generated by Django 6.0.2 on 2026-03-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_aboutyourcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_moto', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('company_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('company_size', models.CharField(max_length=100)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('about', models.TextField()),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutyourCompany',
        ),
    ]
