# Generated by Django 5.2 on 2026-03-26 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_remove_emailotp_user_emailotp_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='phone',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_employer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobapp.job'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('investigating', 'Under Investigation'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='department',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='education',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='industry_type',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_category',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_description',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_highlights',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='key_skills',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='location',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='responsibilities',
            field=models.TextField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'reported_job')},
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='jobapp_comp_status_547c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reported_job', 'status'], name='jobapp_comp_reporte_94482b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', 'reported_job'], name='jobapp_comp_user_id_f4c067_idx'),
        ),
    ]
