# Generated by Django 5.2 on 2026-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_remove_emailotp_phone_complaint_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='department',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='industry_type',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_category',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_highlights',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='key_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='location',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='shift',
            field=models.CharField(choices=[('General', 'General'), ('Night', 'Night'), ('Rotational', 'Rotational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='work_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=50),
        ),
    ]
