# Generated by Django 5.2 on 2026-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_alter_postajob_department_alter_postajob_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='department',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='education',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='industry_type',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_category',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_description',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_highlights',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='key_skills',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='location',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='responsibilities',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Rotational', 'Rotational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='work_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50),
        ),
    ]
