# Generated by Django 5.2 on 2026-03-27 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_postajob_department_alter_postajob_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='department',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_a_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='industry_type',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='key_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
