# Generated by Django 5.2 on 2026-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_postajob_department_alter_postajob_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postajob',
            name='job_status',
            field=models.CharField(choices=[('Hiring in Progress', 'Hiring in Progress'), ('Reviewing Application', 'Reviewing Application'), ('Hiring Done', 'Hiring Done')], default='Reviewing Application', max_length=50),
        ),
    ]
