# Generated by Django 5.2 on 2026-03-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_postajob_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobapp.postajob'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reported_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobapp.postajob'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobapp.postajob'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
