# Generated by Django 5.2 on 2026-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageknown',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='languageknown',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='languageknown',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_language_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_skill_per_profile'),
        ),
    ]
